### ISSUE TITLE
package-lock.json only ignored when should be disabled

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#103]
Running `npm install` on `master` both creates and reads a possibly existing `package-lock.json`. It prints this message in the former case:
> `npm notice created a lockfile as package-lock.json. You should commit this file.`

51c7645f1eafaf08fb85151ec6f0ecf1a21eab34 only removed `package-lock.json` from VCS. If we'd like to work sans `package-lock.json`, then npm should be told. PR coming up.

**Comment by feross** [comment]
Sounds good! I usually just set:

```
package-lock=false
```

in my personal `.npmrc` file, since I mostly do module development. But you can add one to this repo if you'd like too.
