### ISSUE TITLE
Error: Definition for rule '@typescript-eslint/key-spacing' was not found.  @typescript-eslint/key-spacing

### ISSUE THREAD

**Issue by loick** [standard/eslint-config-standard-with-typescript#1050]
Hi there 👋
 In the last version of the library (v34.0.0), I now have this error during my build on each typescript file:

> 1:1  Error: Definition for rule '@typescript-eslint/key-spacing' was not found.  @typescript-eslint/key-spacing

I don't see anything specific to do on the [release notes](https://github.com/standard/eslint-config-standard-with-typescript/blob/HEAD/CHANGELOG.md#%E2%80%8B3400-httpsgithubcomstandardeslint-config-standard-with-typescriptcomparev3300v3400-2023-02-01). Any idea? 

Thanks 🙏

**Comment by mightyiam** [comment]
Sorry about that. Please update your `@typescript-eslint/eslint-plugin` to v5.50.0.

We'll think about how to prevent this from happening again.

**Comment by loick** [comment]
Sure no pb, thanks for the quick answer! 🙏

**Comment by mightyiam** [comment]
You're welcome. Reopening, because we see this as a bug.

**Comment by dvTB** [comment]
For me the error was gone after deleting package-lock.json, removing node_modules folder, installing and that restarting VS code.
Without doing this, eslint always wanted the package "@typescript-eslint/key-spacing'" (which does not at all exist in the npm library)

**Comment by mightyiam** [comment]
Closing in favor of #1064.
