### ISSUE TITLE
@typescript-eslint/strict-boolean-expressions should be "off"

### ISSUE THREAD

**Issue by jribbens** [standard/eslint-config-standard-with-typescript#1072]
The point of "standard" is to enforce a consistent code style, and to catch bugs before runtime. One would expect the same for "ts-standard", and mostly it is. But It has the "strict-boolean-expressions" rule turned on, and that has nothing to do with code style, and nothing to do with catching bugs either. It fundamentally changes the underlying programming language by banning a standard feature of that language! That is bizarre and completely inappropriate for either a style checker or a linter. Please turn the rule off.

**Comment by mightyiam** [comment]
Thank you for the feedback, @jribbens . Our priority is currently #1064. We will get 'round to this later.

**Comment by LinusU** [comment]
I personally like this rule, since it's very easy to accidentally miss that a variable is nullable. e.g. is the code `if (product.price) ...` intending to check if the price is non-null, or wether or not the price is 0?

**Comment by rostislav-simonik** [comment]
> The point of "standard" is to enforce a consistent code style, and to catch bugs before runtime. 

I suppose yes
> One would expect the same for "ts-standard", and mostly it is. But It has the "strict-boolean-expressions" rule turned on, and that has nothing to do with code style, and nothing to do with catching bugs either.

As LinusU pointed out this can catch bugs. 
> It fundamentally changes the underlying programming language by banning a standard feature of that language! 

Well, one could say that typescript changes the language by adding type checking to javascript. 
> That is bizarre and completely inappropriate for either a style checker or a linter. Please turn the rule off.

We understand that it adds additional complexity,  but we feel this trade-off is worth it. 

Still, if you consider this rule too aggressive for your projects, maybe you can explicitly relax it in your eslint config.

**Comment by jribbens** [comment]
@rostislav-simonik 
> Well, one could say that typescript changes the language by adding type checking to javascript.

Yes you could say that, because it's true. But that's fine, because unlike eslint/standard/ts-standard, TypeScript is a language and not a linter.

> We understand that it adds additional complexity, but we feel this trade-off is worth it.

My feeling is that it isn't a "trade-off" at all, because it doesn't further the goals of `eslint-config-standard-with-typescript` - it's all downside, no upside. If the goal of this project is to be "standardjs but for typescript" then this decision causes the project to fail at that goal. (And that's completely aside from the more subjective opinion that the hugely increased complexity mandated by `strict-bool-expressions` is more likely to *increase* bugs than reduce them.)

> Still, if you consider this rule too aggressive for your projects, maybe you can explicitly relax it in your eslint config.

Part of the problem there is that as I understand it, "ts-standard" doesn't allow eslint config. So the only option is not to use it at all - which means my `package.json` is increased in complexity from a single dependency to seven.

**Comment by mightyiam** [comment]
@jribbens, how do you feel about the kind of bug proposed by @LinusU ?

**Comment by jribbens** [comment]
@mightyiam 
> @jribbens, how do you feel about the kind of bug proposed by @LinusU ?

I think a computer cannot distinguish it from not-a-bug. When I write `if (foo)` then I mean "if `foo` evaluates to one of the values that JavaScript/TypeScript defines as meaning true", because that's what that statement means. It is not up to a linter to say "actually we don't think the language designer should have allowed non-boolean condition expressions, so we're going to ban them".

**Comment by mightyiam** [comment]
> I think a computer cannot distinguish it from not-a-bug.

Right. Instead, linters try to sway us from potential oversight.

> "if `foo` evaluates to one of the values that JavaScript/TypeScript defines as meaning true"

This is where potential oversights can be made. A developer can say "I know what I'm doing" but we err on the side of caution.

Other than `false`, up to eight other values are [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy), depending on how you count.

We don't feel like taking the chance. Whatever extra code that is necessary in order to convert that `0` or that `null` into a `false` is probably worth preventing the occasional bug.

> It is not up to a linter to say "actually we don't think the language designer should have allowed non-boolean condition expressions, so we're going to ban them".

I respect your attitude, but many feel differently. For many, this is why they use a linter.

![comparison between JavaScript The Definitive Guide and JavaScript: The Good Parts](https://i.redd.it/h7nt4keyd7oy.jpg)

From day one, this config has been just about as strict as it can and that's by design.

**Comment by rostislav-simonik** [comment]
> > Still, if you consider this rule too aggressive for your projects, maybe you can explicitly relax it in your eslint config.
> 
> Part of the problem there is that as I understand it, "ts-standard" doesn't allow eslint config. So the only option is not to use it at all - which means my `package.json` is increased in complexity from a single dependency to seven.

Personally, I have ended up with the same on our projects. That's the beauty of this package. Even though I'm contributing to this project, not always every rule is the best choice for my projects. We are trying to be objective, at cost of losing subjective benefit. 

There are many options for how to deal with it, it's just a matter of time
* Try to convince us about the opposite
* Eject from ts-standard and install a few more dependencies
* Fork ts-standard create your own version for your personal case. 
* Convince @LinusU to approve PR with the ability to pick local eslint config in ts-standard.

**Comment by rostislav-simonik** [comment]
and obviously one more option
* accept the rule and reflect in your codebase :)

**Comment by mightyiam** [comment]
@jribbens how is this rule contrary to standardjs, please?

**Comment by jribbens** [comment]
> @jribbens how is this rule contrary to standardjs, please?

I've basically already said above. standardjs is simply a prescribed formatting style and some uncontroversial lint options. When I originally switched to using standardjs I had to fiddle with some whitespace but that was basically about it. standardjs does not get in your way and does not tell you how you must write your code.

ts-standard, by contrast, does the above but also says "oh, and by the way, we're switching off a fundamental feature of the language - if you were previously writing TypeScript you're not anymore, we've changed how the language works". It's *not a linter* if it's altering fundamentals of the language. It's like if someone just arbitrarily decided "const is bad, we're gonna ban it in the linter" except worse, because if `const` was banned you'd just replace it with `let` and carry on.

When it comes down to it there is absolutely no way on earth that this:
```javascript
    if (foo.bar)
```
which is compact, extremely clear, and says exactly what I mean ("has `bar` been given a non-empty value?") is better when replaced with:
```javascript
    if (foo.bar !== undefined && foo.bar !== null && foo.bar !== '' &&
        foo.bar !== false && foo.bar !== 0)
```
This rule doesn't find bugs for you - it introduces them. It lowers code quality.

**Comment by jribbens** [comment]
> The above list are all cases of "[language feature] is bad, we're gonna ban it in the linter".

That's not really a fair comparison. Some of them (such as "no var", "no void", "eqeqeq") are because they are language features that have been superceded, some of them (such as "no caller", "no delete var", "no with") are not so much "banned by standardjs" as they are "banned by strict mode", some of them are obscure and rarely used (such as "no labels", "no eval"), and some of them are not banning anything they are just asking you to add some brackets (e.g. "no mixed operators", "no sequences"). None of them are anything like "strict boolean expressions" in fundamentally altering a basic and common use of the language.

> ESLint probably has a few more of these that are not in use by Standard.

Yes. I'm not objecting to eslint having these features, they're optional after all. What I'm objecting to is them being enabled in `ts-standard` where there are no options.

> To understand better how you reached this piece of code — which everyone would agree is undesirable — could you please let us know the type, as far as TypeScript is reporting, of `foo.bar`?

The most common circumstance this sort of thing is coming up for me is where `foo` has come from JSON or a database, so its type as far as TypeScript is concerned is either `any` or something very vague at best.

**Comment by LinusU** [comment]
> The most common circumstance this sort of thing is coming up for me is where foo has come from JSON or a database, so its type as far as TypeScript is concerned is either any or something very vague at best.

We could potentially turn on `allowAny`, which would allow doing `if (foo)` if `foo` is of type `any`...

-----

> it just seems bizarre that what I want is "standardjs for TypeScript", there is a project that claims to be "standardjs for TypeScript", and I can't use it because it isn't "standardjs for TypeScript".

This is actually something I've been thinking about before, and there certainly is a bit of a difference in the philosophy between `standard` and `ts-standard`.

For me, something that aims to be strict and value correctness (as I believe `ts-standard` currently does) is more valuable, and is what I want to use.

That being said, I can see how people coming from `standard` would be a bit surprised by this...

🤔

**Comment by jribbens** [comment]
> > The most common circumstance this sort of thing is coming up for me is where foo has come from JSON or a database, so its type as far as TypeScript is concerned is either any or something very vague at best.
> 
> We could potentially turn on `allowAny`, which would allow doing `if (foo)` if `foo` is of type `any`...

That's kind've a step in the right direction I suppose, but also a step in the wrong direction since it encourages the use of `any`...
 
> > it just seems bizarre that what I want is "standardjs for TypeScript", there is a project that claims to be "standardjs for TypeScript", and I can't use it because it isn't "standardjs for TypeScript".
> 
> This is actually something I've been thinking about before, and there certainly is a bit of a difference in the philosophy between `standard` and `ts-standard`.
> 
> For me, something that aims to be strict and value correctness (as I believe `ts-standard` currently does) is more valuable, and is what I want to use.
> 
> That being said, I can see how people coming from `standard` would be a bit surprised by this...

Exactly. Feel free to make and publish as many lists of whatever eslint rulesets you want... but don't call it "standard for typescript" if it's you're going to make choices which are very surprising to users of standard.
