### ISSUE TITLE
Option to include JS-Files

### ISSUE THREAD

**Issue by falco467** [standard/eslint-config-standard-with-typescript#1088]
**What version of this package are you using?**
34.0.1

**What problem do you want to solve?**
I'm working with a codebase consisting of .js, .svelte and .astro files. All of them including JSDoc annotated JavaScript code with full type-information. All of this is correctly parsed by @typescript-eslint/parser. If I enable the rules globally or by using `plugin:@typescript-eslint/recommended-requiring-type-checking` the rules like no-floating-promises work in all files without problem.

I would like to use the ts-standard rules in this codebase, but I see no way to enable the rules globally or for other file-types, since the shared config only enables the rules in the override-section for ts and tsx files.

**What do you think is the correct solution to this problem?**
Maybe provide an option to enable the rules globally instead of just inside the override for ts-files? Or is there a way I could reference the rules in my ESLint-Config like this: ```rules: { ...standardWithTypescript.getRules(), ...} ``` ?

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by mightyiam** [comment]
Highest priority is currently #1149, which seems would resolve this.
