### ISSUE TITLE
Missing support for `.mtsx?` `.ctsx?`

### ISSUE THREAD

**Issue by loynoir** [standard/eslint-config-standard-with-typescript#1115]
**What version of this package are you using?**
https://github.com/standard/eslint-config-standard-with-typescript/blob/1c645d9fe445e1a57363fac3ead9519977c566eb/src/index.ts#L50

**What operating system, Node.js, and npm version?**

**What happened?**

```ts
type reproduce = 42
```

```sh
$ npm exec -- eslint ./reproduce.mts

/path/to/reproduce.mts
  1:6  error  Parsing error: Unexpected token reproduce

✖ 1 problem (1 error, 0 warnings)
```

**What did you expect to happen?**

Something like
```js
files: ['*.ts', '*.tsx', '*.mts', '*.cts', '*.mtsx', '*.ctsx'],
```

But enforce ESM rule for `.mtsx?`, enforce CJS rule for `.ctsx?`, under style-of-standard.

**Are you willing to submit a pull request to fix this bug?**

**Reference**

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#new-file-extensions

**Comment by mightyiam** [comment]
Thank you. We'll take a look at this. Highest priority is currently #1149, which seems related.

**Comment by mightyiam** [comment]
This should have been solved by v36. Could you please reopen if not?
