### ISSUE TITLE
Our config to not be under the overrides property

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#1149]
#43 was never a good idea. We mean to revert it, probably as a breaking change.

This happens to be the highest priority issue at this time.

**Comment by jf-niji** [comment]
Hello,

I wonder why you make this decision. Is it related to ESLint v9 with the new config file format? 🤓

Regards.

**Comment by mightyiam** [comment]
Nah, it's not inspired by that. I don't even know what that change includes.

#43 was never a good idea because it is implemented using the overrides feature with a filename extensions pattern. That is way too specific and stepping outside of the scope of this package. Specifically, it prevents users from applying this config to whatever arbitrary filename extensions they may wish to apply it to. `*.js` definitely comes to mind. And we did get #1088 reported, which prompted rethinking of this.
