### ISSUE TITLE
@typescript-eslint/parser should be fixed dependency

### ISSUE THREAD

**Issue by jordan-jarolim** [standard/eslint-config-standard-with-typescript#1179]
**What version of this package are you using?**
36.0.0

**What operating system, Node.js, and npm version?**
MacOs, yarn 3.5.1, nodejs 16.15.1

**What happened?**
```
Error: .eslintrc.js » eslint-config-standard-with-typescript:

Configuration for rule "@typescript-eslint/restrict-plus-operands" is invalid:

Value {"checkCompoundAssignments":true} should NOT have additional properties.
```

The error above is caused by the fact that there were breaking changes in @typescript-eslint/parser between 5.50 and 5.60 (https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.60.0). This project only defines the version with a caret, so the peer dependency got automatically upgraded to 5.60 and this caused the issue. 

EDIT: the change was actually introduced here: https://github.com/typescript-eslint/typescript-eslint/commit/dc801d892ecc1af678ff37166481f4b69186164c it is not listed in the changelog though.

**What did you expect to happen?**

I expect this project to have fixed dependencies.

**Are you willing to submit a pull request to fix this bug?**
Sure

**Comment by kherock** [comment]
This isn't true - the error mentioned for `{"checkCompoundAssignments":true}` is a breaking change for version 6.0. The commit you linked was never part of the 5.x tag.

**Comment by jordan-jarolim** [comment]
Hi, ok could be that I got confused by browsing their commits. Nevertheless, could you give me a hint why this error is happening then? Also, aren't pinned dependencies a good practice? Thanks for creating a pull request already.

**Comment by kherock** [comment]
You or one of your dependencies has installed version 6 of `@typescript-eslint` into your project's modules. `eslint-config-standard-with-typescript` is correctly pinning `^5.50.0` in its supported peerDependencies range, and modern versions of `npm` will automatically select the correct one:

```
❯ npm i -D @typescript-eslint/eslint-plugin eslint-config-standard-with-typescript

added 212 packages, and audited 213 packages in 28s

89 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
❯ cat package.json
{
  "name": "npmtest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.62.0",
    "eslint-config-standard-with-typescript": "^36.0.0"
  }
}
```

If you try to force `@typescript-eslint` to an newer version, you're normally greeted with an error unless you're on an older version of npm, or install with `--force` or `--legacy-peer-deps`:

```
❯ npm i -D @typescript-eslint/eslint-plugin@6
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: npmtest@1.0.0
npm ERR! Found: @typescript-eslint/eslint-plugin@5.62.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   peer @typescript-eslint/eslint-plugin@"^5.50.0" from eslint-config-standard-with-typescript@36.0.0
npm ERR!   node_modules/eslint-config-standard-with-typescript
npm ERR!     dev eslint-config-standard-with-typescript@"^36.0.0" from the root project
npm ERR!   dev @typescript-eslint/eslint-plugin@"6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @typescript-eslint/eslint-plugin@"6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @typescript-eslint/parser@6.0.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   peer @typescript-eslint/parser@"^6.0.0 || ^6.0.0-alpha" from @typescript-eslint/eslint-plugin@6.0.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

To fix it, make sure that you've explicitly pinned `"@typescript-eslint/eslint-plugin": "^5.62.0"` in your package.json.

**Comment by SimpleCreations** [comment]
Are there any plans to support typescript-eslint v6?

**Comment by mightyiam** [comment]
Of course.

**Comment by TanyaKars** [comment]
Are there any time frames for fixing this?

**Comment by mightyiam** [comment]
Next session is scheduled for July 22nd. Perhaps then we will examine.

**Comment by mightyiam** [comment]
If I am to understand that this issue is asking the parser to be a pinned dependency, then I don't see how that would work, considering the plugin is not pinned. If anyone wants to make this issue about anything else, or otherwise disagrees, feel free to comment.
