### ISSUE TITLE
The checkCompoundAssignments property is not supported by @typescript-eslint/restrict-plus-operands

### ISSUE THREAD

**Issue by faner11** [standard/eslint-config-standard-with-typescript#1185]
**What version of this package are you using?**
36.1.0
**What operating system, Node.js, and npm version?**
v18.16.1 pnpm 8.61
**What happened?**
```
Error: .eslintrc.cjs#overrides[0] » eslint-config-standard-with-typescript:
        Configuration for rule "@typescript-eslint/restrict-plus-operands" is invalid:
        Value {"checkCompoundAssignments":true} should NOT have additional properties.
```
https://typescript-eslint.io/rules/restrict-plus-operands/
https://github.com/typescript-eslint/typescript-eslint/pull/7027
![image](https://github.com/standard/eslint-config-standard-with-typescript/assets/26560612/1b13495d-f90d-4026-9034-3a3faba6792f)

**What did you expect to happen?**
Change to a value that can be supported

**Are you willing to submit a pull request to fix this bug?**
Yes, can I change it to?

```
    "@typescript-eslint/restrict-plus-operands": {
    skipCompoundAssignments :false;

}

```

**Comment by faner11** [comment]
@mightyiam [6.1.0](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin/v/6.1.0)

**Comment by mightyiam** [comment]
Sorry, that's not supported yet.

https://github.com/standard/eslint-config-standard-with-typescript/blob/722d2b550a5090231db691e8f1421d4e78d29285/package.json#L60

**Comment by temahot** [comment]
@mightyiam Hi! 
What about @typescript-eslint/eslint-plugin [6.1.0](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin/v/6.1.0) ?
