### ISSUE TITLE
Add support for @typescript-eslint version 6.x.x

### ISSUE THREAD

**Issue by jerome-benoit** [standard/eslint-config-standard-with-typescript#1188]
**What version of this package are you using?**

36.1.0

**What problem do you want to solve?**

Crash at running the linter: 

```
ESLint: 8.45.0

Error: .eslintrc.js#overrides[0] » eslint-config-standard-with-typescript:
        Configuration for rule "@typescript-eslint/restrict-plus-operands" is invalid:
        Value {"checkCompoundAssignments":true} should NOT have additional properties.

    at ConfigValidator.validateRuleOptions (/Users/I339261/SAPDevelop/poolifier-git/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2039:23)
    at /Users/I339261/SAPDevelop/poolifier-git/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2094:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Users/I339261/SAPDevelop/poolifier-git/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2091:34)
    at ConfigValidator.validateConfigArray (/Users/I339261/SAPDevelop/poolifier-git/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2217:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/I339261/SAPDevelop/poolifier-git/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3974:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/I339261/SAPDevelop/poolifier-git/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3780:21)
    at FileEnumerator._iterateFilesRecursive (/Users/I339261/SAPDevelop/poolifier-git/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/cli-engine/file-enumerator.js:450:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/I339261/SAPDevelop/poolifier-git/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:49)
```

**Comment by mightyiam** [comment]
Is this still an issue, please? May I see the output of `npm ls`, please?

**Comment by jerome-benoit** [comment]
Yes. To reproduce, you just need to install 

"eslint": "^8.45.0",
"eslint-config-standard-with-typescript": "^36.1.0",
"@typescript-eslint/eslint-plugin": "^6.1.0",
"@typescript-eslint/parser": "^6.1.0",

in a dummy app, configure eslint with documented defaults for eslint-config-standard-with-typescript and @typescript-eslint and run the linter.

**Comment by karolyi** [comment]
`37.0.0` didn't fix this, as I thought it would from the major version bump:

```npm
npm ERR! Found: @typescript-eslint/eslint-plugin@6.1.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^6.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/eslint-plugin@"^5.52.0" from eslint-config-standard-with-typescript@37.0.0
npm ERR! node_modules/eslint-config-standard-with-typescript  
npm ERR!   dev eslint-config-standard-with-typescript@"^37.0.0" from the root project

```

**Comment by Jayprecode** [comment]
Are there any fixes for this error, i'm also facing the same issue

**Comment by Jayprecode** [comment]
> `37.0.0` didn't fix this, as I thought it would from the major version bump:
> 
> ```
> npm ERR! Found: @typescript-eslint/eslint-plugin@6.1.0
> npm ERR! node_modules/@typescript-eslint/eslint-plugin
> npm ERR!   dev @typescript-eslint/eslint-plugin@"^6.1.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @typescript-eslint/eslint-plugin@"^5.52.0" from eslint-config-standard-with-typescript@37.0.0
> npm ERR! node_modules/eslint-config-standard-with-typescript  
> npm ERR!   dev eslint-config-standard-with-typescript@"^37.0.0" from the root project
> ```

were you able to resolve this?

**Comment by karolyi** [comment]
> Hi [karolyi](https://github.com/karolyi), were you able to resolve this?

Yes, by downgrading the required packages.

**Comment by mightyiam** [comment]
This project doesn't support typescript-eslint v6 yet. Your package manager should be telling you that.

Also, supporting it seems non-trivial. So it may take a while.

**Comment by Mist3rBru** [comment]
To workaround this issue, install the fallowing packages at v5:

```sh
npm install -D @typescript-eslint/eslint-plugin@5 @typescript-eslint/parser@5
```

**Comment by retrixe** [comment]
With Yarn v2+'s `yarn patch eslint-config-standard-with-typescript` I was able to get this config working with TypeScript ESLint v6, see here for the patch https://github.com/retrixe/ecthelion/blob/main/.yarn/patches/eslint-config-standard-with-typescript-npm-37.0.0-e24fa6a048.patch

Presumably npm patch-package can do this for you as well.

**Comment by jerome-benoit** [comment]
@retrixe: please do a pull request on that repo including the code changes in the patch. 
The package maintainer(s) as well as their users will be thankful to you for having made the groundwork to start supporting @typescript-eslint version 6.x.x

**Comment by retrixe** [comment]
> @retrixe: please do a pull request on that repo including the code changes in the patch. The package maintainer(s) as well as their users will be thankful to you for having made the groundwork to start supporting @typescript-eslint version 6.x.x

#1222
