### ISSUE TITLE
Configuration for rule "@typescript-eslint/array-type" is invalid

### ISSUE THREAD

**Issue by fibo** [standard/eslint-config-standard-with-typescript#125]
**What version of this package are you using?**

I am using *@typescript-eslint/eslint-plugin* `v2.0.0`, follows list of other relevant development dependencies

```json
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.0.0",
    "eslint": "^6.1.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "typescript": "^3.5.2"
  }
```

**What operating system, Node.js, and npm version?**

MacOS Mojave 10.16.6

```bash
$ node -v
v12.1.0
$ npm -v
6.9.0
```

**What happened?**

```
Error: .eslintrc.json » eslint-config-standard-with-typescript#overrides[0]:
	Configuration for rule "@typescript-eslint/array-type" is invalid:
	Value "array-simple" should be object.
```

**What did you expect to happen?**

I am migrating from tslint, I expected linter warnings but a working eslint configuration.

You can reproduce quickly this error by cloning this repo https://github.com/go-seven/go-seven.com/tree/eslint-config-standard-with-typescript

checking out the *eslint-config-standard-with-typescript* branch, then run

```bash
npm install
npm run linter
```

**Are you willing to submit a pull request to fix this bug?**

Why not, if the author can give me some hint I can try to provide a PR.

**Comment by mightyiam** [comment]
I apologize about this, @fibo. Thank you for submitting an issue. Could you please use `"@typescript-eslint/eslint-plugin": "^1.10.1"`?

The readme is misleading. Here's the issue #123 .
