### ISSUE TITLE
Configuration for rule "@typescript-eslint/restrict-plus-operands" is invalid

### ISSUE THREAD

**Issue by 5war00p** [standard/eslint-config-standard-with-typescript#1250]
**What version of this package are you using?**
^39.0.0
**What operating system, Node.js, and npm version?**
Windows 10
Node - v18.16.0
NPM - 9.5.1
**What happened?**
![image](https://github.com/standard/eslint-config-standard-with-typescript/assets/57614947/fcb66439-9a49-46b7-a277-f87c70179ce7)

**What did you expect to happen?**
Lint should work properly
**Are you willing to submit a pull request to fix this bug?**
No

**Comment by mightyiam** [comment]
What version of `@typescript-eslint/eslint-plugin` do you have?

**Comment by 5war00p** [comment]
Hey @mightyiam, it's `5.46.1`

**Comment by mightyiam** [comment]
That's incompatible. Your package manager should inform you of that. See our peerDeps.

**Comment by FedericoBiccheddu** [comment]
@mightyiam same problem with v`6.7.2`.

```
devDependencies:
eslint-config-standard-with-typescript 39.0.0
└── @typescript-eslint/eslint-plugin 6.7.2 peer
```

```
Error: .eslintrc.js » eslint-config-standard-with-typescript:
	Configuration for rule "@typescript-eslint/restrict-plus-operands" is invalid:
	Value {"skipCompoundAssignments":false} should NOT have additional properties.
```

This is my `eslintrc.js`
```js
module.exports = {
  extends: ['standard-with-typescript', 'prettier'],
  parserOptions: {
    project: './tsconfig.json',
    sourceType: 'module',
  },
}
 ```
