### ISSUE TITLE
Add @toddbluhm to the org

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#139]
Hi, @toddbluhm, @feross,

@toddbluhm has been reviewing my work in this repo and he recently launched https://github.com/toddbluhm/ts-standard (charming readme!), which depends on this repo.

@feross, how about inviting @toddbluhm to the org?

**Comment by feross** [comment]
Of course. @toddbluhm you should have received an invite!

Agreed, the readme is quite charming :)

**Comment by toddbluhm** [comment]
@feross received it and just accepted it. Thank you very much for the invite! 

Anything I can do to help move `standard` forward, especially in regards to `typescript` support and improvements. If you have any recommendations on the project or see any discrepancies between `standard` and `ts-standard` let me know, and I can work to resolve them. Thank you both @mightyiam and @feross for all the hard work you have put in on `standard` 🎉

**Comment by mightyiam** [comment]
Thank you :1st_place_medal: :pray:
