### ISSUE TITLE
Include rule prefer-includes

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#148]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-includes.md

**Comment by toddbluhm** [comment]
I think this is a good rule to add. My only concern is people writing pre-es2015 code. But then again if they are writing pre-es2015 code they probably are not using this configuration.

**Comment by mightyiam** [comment]
@toddbluhm thank you for your suggestion. I agree that this should be included. Would you like to PR?
