### ISSUE TITLE
[require-await] Conflicts with promise-function-async

### ISSUE THREAD

**Issue by swansontec** [standard/eslint-config-standard-with-typescript#158]
**What version of this package are you using?**

v9

**What happened?**

Suppose you want to make a function that returns a promise:

```typescript
function foo(): Promise<number> {
  return Promise.resolve(1)
}
```

You will get `@typescript-eslint/promise-function-async` complaining, which makes sense. This is a good rule, since it ensures functions that return promises will never throw ordinary exceptions, only rejected promises. So, we fix it:

```typescript
async function foo(): Promise<number> {
  return 1
}
```

Now we get `@typescript-eslint/require-await`, since we don't actually await anything. Therefore, the two rules create an impossible problem if you are trying to implement an async API, but don't actually need to wait for anything.

You might say, "Just don't return a promise in this case," but that doesn't work in a lot of cases where external libraries / API requirements force you to return promises. This might happen if you are mocking `async` functions in a unit test, for instance, but the mocks just return static data.

The simplest solution is to remove `@typescript-eslint/require-await`, since it doesn't make any sense in the context of `@typescript-eslint/promise-function-async` - functions might need to be `async` even if they don't `await`.

**Comment by mightyiam** [comment]
Thank you, @swansontec, for the suggestion.

Would this work with the rules as they are?

```
async function foo(): Promise<number> {
  return Promise.resolve(1)
}
```

And did you read https://github.com/standard/standard/issues/1442?

**Comment by swansontec** [comment]
I was not aware of that other proposal, but removing `no-return-await` would fix this issue neatly.

Also, the example you give does actually work with the current rules! Somehow I missed this possibility. I looks like the `@typescript-eslint/require-await` rule is "smart" about the types, and won't trigger if the return type is already a promise. I didn't realize it was doing this.

**Comment by mightyiam** [comment]
Thank you for following up, @swansontec. So... I'm closing this, because I understand we found a pattern you can use, right?

**Comment by swansontec** [comment]
Yep, that's fine. Sorry for the trouble!
