### ISSUE TITLE
Renovate

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#178]
@feross could you please enable [Renovate](https://github.com/marketplace/renovate) for this repository?

**Comment by mightyiam** [comment]
Kind ping @feross. I'll handle the configuration. If you would just install the GitHub app and give it access to this repository, please. If you find the permissions acceptable. Unlike other tools, it does not ask for admin write permissions.

**Comment by mightyiam** [comment]
@LinusU here's a reminder to set me up with owner status on the org, please.

**Comment by LinusU** [comment]
I think I manage to add Renovate, Feross should be able to fix your permissions

**Comment by mightyiam** [comment]
Thank you, @LinusU!
