### ISSUE TITLE
no-dupe-class-members is not disabled and not compatible with function overload

### ISSUE THREAD

**Issue by Gerhut** [standard/eslint-config-standard-with-typescript#213]
**What version of this package are you using?**

11.0.1

**What operating system, Node.js, and npm version?**

macOS, v12.4.0 v6.9.0

**What happened?**

The following code

```ts
  constructor (state: IssueState);
  constructor (expected: string, actual: string);
  constructor (stateOrExpected: IssueState | string, actual?: string) {
    super()
    if (stateOrExpected instanceof IssueState) {
      this.expected = stateOrExpected.expected
      this.actual = stateOrExpected.actual
    } else if (typeof actual === 'string') {
      this.expected = stateOrExpected
      this.actual = actual
    } else {
      throw TypeError(`Invalid actual: ${actual}`)
    }
  }
```

Constructor overload causes lint error.

```
8:3  error  Duplicate name 'constructor'  no-dupe-class-members
9:3  error  Duplicate name 'constructor'  no-dupe-class-members
```

**What did you expect to happen?**

No lint error here

**Are you willing to submit a pull request to fix this bug?**

Nope, it seems `plugin:@typescript-eslint/eslint-recommended` disabled this rule in https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts#L29

Not sure our plan to inherit `plugin:@typescript-eslint/eslint-recommended` or write our owned.

**Comment by mightyiam** [comment]
Thank you for using Standard, @Gerhut and for your report.

This seems to be known [upstream](https://github.com/typescript-eslint/typescript-eslint/issues/291).

We don't use or follow upstream's recommended config.

I feel that we should disable this rule.

**Comment by mightyiam** [comment]
Actually, this is already not in our config. I haven't released for a while.

**Comment by mightyiam** [comment]
I went back as far as v8.0.0 and I didn't find the rule no-dupe-class-members in this config. So either you're using a very old version or we never had it. In any case, we don't have it now, I'm quite sure. Oh, wait. I get it now. It's not a typescript-eslint rule. It's a core eslint rule. Will fix.

**Comment by mightyiam** [comment]
And v12.0.1 released with a fix for this :wine_glass:
