### ISSUE TITLE
func-call-spacing and comma-dangle can cause un-fixable error

### ISSUE THREAD

**Issue by felskov** [standard/eslint-config-standard-with-typescript#232]
In the following example, I'm getting an error from func-call-spacing:

```ts
const map = new Map<string, () => void>()
```

Auto-fixing results in the following code, which throws an error from comma-dangle:

```ts
const map = new Map<string,() => void>()
```

**What version of this package are you using?**
13.0.0

**What problem do you want to solve?**
Avoid having un-fixable errors using out-of-the-box configuration

**What do you think is the correct solution to this problem?**
Use @typescript-eslint/func-call-spacing instead of eslint built-in func-call-spacing.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/func-call-spacing.md

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by LinusU** [comment]
> Use @typescript-eslint/func-call-spacing instead of eslint built-in func-call-spacing.

This sounds great, PR welcome 🙌

**Comment by felskov** [comment]
@LinusU  https://github.com/standard/eslint-config-standard-with-typescript/pull/234
