### ISSUE TITLE
Consider allowing interpolating numbers into template literals

### ISSUE THREAD

**Issue by LinusU** [standard/eslint-config-standard-with-typescript#239]
**What version of this package are you using?** 5.0.0

**What problem do you want to solve?**

I'm trying to format an error message to the user:

```typescript
const onFailedAttempt: OnFailedAttempt = (error) => {
  return `Långsam uppkoppling, försöker ${error.attemptNumber} av ${error.attemptNumber + error.retriesLeft}`
}
```

This gives me the following error:

> Invalid type of template literal expression.

**What do you think is the correct solution to this problem?**

I think that we should allow numbers to be interpolated into strings. The semantics are very straight forward, and I don't see what would be better by forcing the usage of `${String(foobar)}`?

**Are you willing to submit a pull request to implement this change?** yes

-----

(I think that keeping `allowBoolean` and `allowNullable` as `false` is the right way to go 👍)

**Comment by mightyiam** [comment]
Closed in #240 .
