### ISSUE TITLE
Using prettier with this config

### ISSUE THREAD

**Issue by simonrussell** [standard/eslint-config-standard-with-typescript#270]
**What version of this package are you using?**
15.0.1

**What problem do you want to solve?**
I'd like to be able to use this with prettier, without it conflicting.  The issue I'm facing is that prettier doesn't put spaces before `constructor`.

**What do you think is the correct solution to this problem?**
Both are correct really, and if I could configure prettier I would.  But probably a more useful thing would be some advice on how to disable the formatting side of this preset?

**Are you willing to submit a pull request to implement this change?**
Sure, but I don't know where to start :)

**Comment by mightyiam** [comment]
Thank you for using this package, @simonrussell and for making your suggestion. So, you'd like to be able to exclude the formatting / style rules. I understand. Does ESLint have a syntax of using a specific set of rules from a shareable config?

**Comment by simonrussell** [comment]
I have not much idea about eslint to be honest. I've been using this via ts-standard, and in other projects it's been set up before I got to it :)

**Comment by mightyiam** [comment]
It seems [supported](https://eslint.org/docs/developer-guide/shareable-configs#sharing-multiple-configs).

@simonrussell if you'd like to give it a go, here's a general plan:

In order to allow this usage:

```js
module.exports = {
  extends: 'standard-with-typescript/sans-style'
}
```

1. Read the [short chapter on extending](https://eslint.org/docs/user-guide/configuring#extending-configuration-files).
1. split our config (`/src/index.ts`) into separate modules:
   1. `/src/non-style.ts`
   1. `/src/style.ts`
   1. `/src/index.ts`: extends from both
1. Provide a convenience `/sans-style.js` with contents:
   ```js
   module.exports = require('./lib/non-style')
   ```
1. Adjust tests accordingly.

**Comment by simonrussell** [comment]
Thanks for that, seems very doable. I might give it a go on the weekend with some of my newly found free time... :)

**Comment by leodr** [comment]
With [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier) you can turn off all stylistic rules that might conflict with prettier. I use that with eslint-config-standard-with-typescript.

**Comment by Divlo** [comment]
I opened a PR in `standard-engine` to add the support for `prettier` : https://github.com/standard/standard-engine/pull/231
Se we could introduce `prettier` for every packages of `standard`, in particular `ts-standard` that uses this repo config.
Currently I used `ts-standard` (this config), with `prettier` in my IDE with this `.prettierc.json` config :
```json
{
  "singleQuote": true,
  "jsxSingleQuote": true,
  "semi": false,
  "trailingComma": "none"
}
```

 I didn't have any conflict issue with `eslint` rules and it seems to work fine.

**Comment by Divlo** [comment]
To use `prettier` with this `eslint` config, you need to have `.prettierrc.json` with this content:
```json
{
  "singleQuote": true,
  "jsxSingleQuote": true,
  "semi": false,
  "trailingComma": "none"
}
```
And `.eslintrc.json` with:
```json
{
  "extends": ["standard-with-typescript", "prettier"],
  "plugins": ["prettier"],
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "rules": {
    "prettier/prettier": "error"
  }
}
```
The dependencies needed are (in addition to the dependencies of our README) : `npm install --save-dev eslint-config-prettier eslint-plugin-prettier`.
As stated in the [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) README ():
> `"extends": ["prettier"]` enables the config from eslint-config-prettier, which turns off some ESLint rules that conflict with Prettier.

Closing as it is not an issue. :smile: 
Please reopen if you struggle to setup `prettier` with this `eslint` config.
Here is my repo as an example: https://github.com/Divlo/Divlo
