### ISSUE TITLE
eslint-config-semistandard-with-typescript?

### ISSUE THREAD

**Issue by lemoustachiste** [standard/eslint-config-standard-with-typescript#276]
**What version of this package are you using?**
15.0.1

**What problem do you want to solve?**
I am coming to this package as I am looking at not installing `tslint` since it's going in deprecation. Our code style follows semistandard, and I would like to configure eslint for typescript following this style. For tslint we are using: tslint-config-semistandard. But it seems this is not available for eslint. 

**What do you think is the correct solution to this problem?**
I am not sure, hence why I am opening this issue. I tried overriding the `rules` property in my project's .eslintrc.js file, similarly as to what `eslint-config-semistandard` does, but that generated more errors and broke snazzy, so I am assuming this is not the right way.

**Are you willing to submit a pull request to implement this change?**
Yes, provided I am guided on the right way to handle this.

**Comment by mightyiam** [comment]
Thank you for using this config, @lemoustachiste. When using standard, you can't use a configuration file. That's part of the concept. Perhaps you'd like to use standardx or plain eslint extending from this config.

**Comment by LinusU** [comment]
@lemoustachiste you should be able to use use and extend `eslint-config-standard-with-typescript` if you are using ESLint directly, and not via `standard` or `ts-standard`.

add this to `.eslintrc.json`:

```json
{
  "extends": "standard-with-typescript",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "rules": {
    "semi": "off",
    "@typescript-eslint/semi": ["error", "always"]
  }
}
```

run this long command:

```sh
npm install --save-dev eslint@6 eslint-plugin-standard@4 eslint-plugin-promise@4 eslint-plugin-import@2 eslint-plugin-node@11 @typescript-eslint/eslint-plugin@2 eslint-config-standard-with-typescript
```

What errors did you get?

-----

@mightyiam we have always supported overriding rules in the `eslint-config-standard*` repos, so I think that we should do that here as well ☺️

**Comment by lemoustachiste** [comment]
Hi @mightyiam,

I'm sorry I think there might have been a misunderstanding. I am not trying to change a lot much from what standard offers. I only want semistandard, but applicable to typescript. Semistandard is supported by this organization: https://github.com/standard/eslint-config-semistandard.

@LinusU you reopened as I was typing. Thanks for your direction, I will try that.

**Comment by mightyiam** [comment]
@lemoustachiste forgive me. I thought you were trying to configure standard. The example provided by @LinusU should be sufficient. Thank you, @LinusU.

**Comment by raiseandfall** [comment]
@LinusU it worked for me. Thanks!

**Comment by AntonOfTheWoods** [comment]
@flisboac , I think most of us typescripters who see semi as a deal-breaker only care about this rule. But the zealotry on this is a major turnoff. If I didn't have to memorize several rules that will never get caught by an IDE, I might think about it but nosemi is *objectively* just dumb. But it shouldn't be part of `standard`, it should be part of the language, period! Or rather semi-colon ;)

**Comment by flisboac** [comment]
@AntonOfTheWoods I fully agree, but it is what it is... :(

I still think this issue should be reopened.

I understand they want to segregate the userbase between semi and non-semi. I honestly don't think the nosemi side of the debate has any good arguments in favor of it, and I frankly don't care about any reasonong anymore. I just don't get why they oppose so much to create the semistandard counterpart on the TypeScript side. Such unbalance makes no sense.

Still, I truly hope they reconsider, and create a fully complete "ts-semistandard" already. I'd switch to it instantly. The editor/IDE tooling is just as important as the standard itself.
