### ISSUE TITLE
Cut 15.0.2 release

### ISSUE THREAD

**Issue by LinusU** [standard/eslint-config-standard-with-typescript#278]
I would like a new release since #217 is affecting me in yet another project ☺️ 

@mightyiam  I figured it would be good if I learned how to cut a release as well, so that we are more than one person who can do this. Have I understood it correctly that all I need to do is `npm run release` to run standard-release? 🙌

**Comment by mightyiam** [comment]
I released v16.0.0 and opened #280 for your review.
