### ISSUE TITLE
Changes to naming-convention causing problems, incompatible with React

### ISSUE THREAD

**Issue by LinusU** [standard/eslint-config-standard-with-typescript#332]
**What version of this package are you using?**

18.0.1

**What operating system, Node.js, and npm version?**

macOS, Node 14, npm 6

**What happened?**

I can no longer declare react components:

```ts
const MyComponent: React.FC = () => (
  <div>Test</div>
)
```

```text
Variable name MyComponent must match one of the following formats: camelCase, UPPER_CASE (@typescript-eslint/naming-convention)
```

**What did you expect to happen?**

This should be okay

**Are you willing to submit a pull request to fix this bug?**

yes

**Comment by Divlo** [comment]
Closing as it is already fixed, thanks to #333.
