### ISSUE TITLE
Turn on `ignoreRhs` on `strict-boolean-expressions`

### ISSUE THREAD

**Issue by LinusU** [standard/eslint-config-standard-with-typescript#369]
**What version of this package are you using?**

Latest

**What problem do you want to solve?**

In React it's very common to do something like this:

```js
<div>
  {showPerson && <Person />}
</div>
```

This is currently not allowed by `strict-boolean-expressions`, and instead it requires us to type:

```js
<div>
  {!showPerson ? null : <Person />}
</div>
```

**What do you think is the correct solution to this problem?**

Turning on `ignoreRhs` would allow this, as specified:

> `ignoreRhs` to skip the check on the right hand side of expressions like `a && b` or `a || b` - allows these operators to be used for their short-circuiting behavior

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by mightyiam** [comment]
Is this relevant with the latest version of the rule? There doesn't seem to be this option:
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md

**Comment by LinusU** [comment]
Hmm, interesting, I literally looked up that option earlier today 😄 obviously I must have made some kind of misstake 🤔 

Looking into it!

**Comment by LinusU** [comment]
closing this until I have looked at it properly, sorry for not investigating properly before opening 😅

**Comment by hagaigold** [comment]
can we reopen it and maybe change the issue name to "relaxing strict-boolean-expressions"?\
(also mention [here](https://github.com/standard/eslint-config-standard-with-typescript/issues/246#issuecomment-597709514))

I found it too strict if you try applying it to a large existing codebase. more if the code was just converted from javascript.
a soft relaxing will to embrace the rule defaults, currently, all options are [off](https://github.com/standard/eslint-config-standard-with-typescript/blob/78a3bd2e7f871119d5c380f18fd5b605c5ccdd17/src/index.ts#L127).

personally, I found allowNullableString the most annoying:

#### allowNullableString: false
```ts
let str: string | null = null;

if (str != null && !str) {
  console.log('str is empty (but not nullish)');
}

if (str == null) {
  console.log('str is nullish');
}

if (str == null || !str) {
  console.log('str is nullish or empty');
}

if (str != null && str) {
  console.log('str is someting');
}

```

#### allowNullableString: true

```ts
let str: string | null = null;

if (!str) {
  console.log('str is not something');
}

if (str) {
  console.log('str is someting');
}

```
