### ISSUE TITLE
@typescript-eslint/no-floating-promises not suitable with no-void

### ISSUE THREAD

**Issue by Gerhut** [standard/eslint-config-standard-with-typescript#370]
**What version of this package are you using?**

18.0.2

**What problem do you want to solve?**

Resolve the `@typescript-eslint/no-floating-promises` with `void promise`, but hit `no-void` enabled in https://github.com/standard/eslint-config-standard/pull/135

**What do you think is the correct solution to this problem?**

Just follow the [official recommendation](https://github.com/typescript-eslint/typescript-eslint/blob/v3.6.0/packages/eslint-plugin/docs/rules/no-floating-promises.md#ignorevoid), turn on the `allowAsAStatement` option in no-void rule.

Or

Disable the `ignoreVoid`.

**Are you willing to submit a pull request to implement this change?**

Sure

**Comment by mightyiam** [comment]
Thank you, @Gerhut, for submitting this issue. In order to best examine this issue, could I ask you to please provide an example code that would trigger `@typescript-eslint/no-floating-promises` in this way that you would like to use `void` to resolve?

**Comment by Gerhut** [comment]
Made a code snippet for details. Run `yarn lint` in the terminal to see the results.

https://codesandbox.io/s/intelligent-shamir-ukib4?file=/index.tsx

**Comment by toddbluhm** [comment]
I am all in favor of setting the `no-void` `allowAsAStatement` option. I have run into this issue a couple of times and it gets to be frustrating with both `no-void` and `@typescript-eslint/no-floating-promises` conflicting with each other. There are ways around the issue, but it gets pretty hacky looking. I typically just disable `no-void` in an eslint comment.

**Comment by mightyiam** [comment]
`allowAsAStatement` seems reasonable. PR welcome.
