### ISSUE TITLE
Leverage fix PR #316 to @typescript-eslint v2

### ISSUE THREAD

**Issue by Gerhut** [standard/eslint-config-standard-with-typescript#371]
**What version of this package are you using?**

17.0.0

**What problem do you want to solve?**

Same as #303 

The latest react-scripts version (3.4.1) is still using @typescript-eslint@^2.10.0

So I cannot simply upgrade @typescript-eslint to v3 as 18.0.0 requires

**What do you think is the correct solution to this problem?**

cherry-pick fix PR #316 to v17.0.0 and release a version v17.0.1

or, more simply, check out https://github.com/standard/eslint-config-standard-with-typescript/commit/1d61c3d620aea9e8a8ca00c488ff8ce61d39f141 and release v17.0.1 

**Are you willing to submit a pull request to implement this change?**

I'm currently maintaining a fork https://github.com/Gerhut/eslint-config-standard-with-typescript/tree/v17 and published an npm package https://www.npmjs.com/package/@gerhut/eslint-config-standard-with-typescript for temporary use.

**Comment by mightyiam** [comment]
Thank you for filing this issue, @Gerhut . I don't feel like investing my open source time in maintaining a previous release. Perhaps use a reasonable workaround until you're able to use v18, or, better yet, contribute to react-scripts?
