### ISSUE TITLE
running eslint gives the error "@typescript-eslint/strict-boolean-expressions" is invalid

### ISSUE THREAD

**Issue by pietervandereems** [standard/eslint-config-standard-with-typescript#376]
**What version of this package are you using?**
eslint-config-standard-with-typescript@18.0.2

**What operating system, Node.js, and npm version?**
OS: Ubuntu linux 20.04
Node.js: v12.18.2
npm: 6.14.5

**What happened?**
$ npx eslint .
Oops! Something went wrong! :(

ESLint: 7.4.0

Error: .eslintrc.js » eslint-config-standard-with-typescript#overrides[0]:
	Configuration for rule "@typescript-eslint/strict-boolean-expressions" is invalid:
	Value {"allowString":false,"allowNumber":false,"allowNullableObject":false,"allowNullableBoolean":false,"allowNullableString":false,"allowNullableNumber":false,"allowAny":false} should NOT have additional properties.

**What did you expect to happen?**
Eslint linting the (simple) server.ts file in that directory.

**Are you willing to submit a pull request to fix this bug?**
Yes.

**Comment by pietervandereems** [comment]
tsconfig.json:
{
  "compilerOptions": {
    "target": "ES2020",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true
  }
}

.eslintrc.js:
module.exports = {
  extends: 'standard-with-typescript',
  parserOptions: {
    project: './tsconfig.json'
  }
}

**Comment by danilocordeiro** [comment]
Hi.

I just run 
npm install --save-dev eslint eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node @typescript-eslint/eslint-plugin eslint-config-standard-with-typescript

without pass the version.

Works for me.

**Comment by pietervandereems** [comment]
@danilocordeiro, thanks. That works a lot better :-)

**Comment by mightyiam** [comment]
Is there a wrong version string in the readme?

**Comment by laurrentt** [comment]
I'm a first time user of this library and I haven't been able to workaround this issue. Installing the packages using the command from the README did not work for me. What should I try next?

**Comment by mightyiam** [comment]
@laurrentt what's the error, please?

**Comment by laurrentt** [comment]
@mightyiam I have the same error that this issue was opened for. 

```
$ npx eslint .

Oops! Something went wrong! :(

ESLint: 7.5.0

Error: .eslintrc.js » eslint-config-standard-with-typescript#overrides[0]:
	Configuration for rule "@typescript-eslint/strict-boolean-expressions" is invalid:
	Value {"allowString":false,"allowNumber":false,"allowNullableObject":false,"allowNullableBoolean":false,"allowNullableString":false,"allowNullableNumber":false,"allowAny":false} should NOT have additional properties.
```

I haven't customize the installation in any way, I'm just getting started. I figured this looked more like a bug than a misconfiguration. The last 2 closed issues on this project are regarding this bug, but unlike their authors I wasn't able to workaround it by removing the specified versions like @danilocordeiro suggested.
