### ISSUE TITLE
Configuration for rule "@typescript-eslint/strict-boolean-expressions" is invalid

### ISSUE THREAD

**Issue by copleykj** [standard/eslint-config-standard-with-typescript#393]
**What version of this package are you using?**

18.0.2

**What operating system, Node.js, and npm version?**

Arco Linux

Node: v14.5.0

NPM: 6.14.5

**What happened?**
(node:1618259) UnhandledPromiseRejectionWarning: Error: package.json » eslint-config-standard-with-typescript#overrides[0]:
	Configuration for rule "@typescript-eslint/strict-boolean-expressions" is invalid:
	Value {"allowString":false,"allowNumber":false,"allowNullableObject":false,"allowNullableBoolean":false,"allowNullableString":false,"allowNullableNumber":false,"allowAny":false} should NOT have additional properties.

**What did you expect to happen?**

This error should not be thrown

**Are you willing to submit a pull request to fix this bug?**

If I knew what caused it, I would have done so already.

------------------------------------------

This seems to be a somewhat persistent issue, with many issues by this title being found listed as closed. I have all the most current packages installed and I'm not able to resolve this. I'm not completely sure of the cause, but from what I can see, this probably deserves a bit more attention than it seems to have gotten in the past.

**Comment by copleykj** [comment]
Restart vscode and error gone. :facepalm:

**Comment by MaykonMorais** [comment]
Hello! I try this but same error appear :cry: 

`
"@typescript-eslint/eslint-plugin": "4",
    "eslint": "7",
    "eslint-config-standard-with-typescript": "^19.0.1",
    "eslint-plugin-import": "2",
    "eslint-plugin-node": "11",
    "eslint-plugin-promise": "4",
    "eslint-plugin-standard": "4",`
