### ISSUE TITLE
conflict in dev-dependency tree

### ISSUE THREAD

**Issue by KilianKilmister** [standard/eslint-config-standard-with-typescript#416]
**What version of this package are you using?**
  "version": "19.0.1",

**What operating system, Node.js, and npm version?**

- node-v14.9.0
- npm-7.0.0-beta.9
- macOS Catalina-v10.15.6

**Current dev deps will not be installable in the upcoming version of NPM**

Npm is tightening dependency resolution with their new engine Arborist, peer dependencies will be automatically installed, and if the peer request can't be fullfilled, npm's default behaviour is to throw an exeption. In this project this happens because of a conflict between `@commitlint/cli@"9.1.2"` and  `commitlint-config-awesome@"1.0.4"` ( peer dependency `@commitlint/cli@"^7.0.0 || ^8.0.0"`).

**Importand edit:** this affects this package distribution: Peer dependencies don't allow the use of **any prerelease** unless they are **specifically mentioned**. obviously causing an issue having typescript in qour peer-deps

There are discusions about peer-deps handeling in npm-v7, but this is intended to stay the **default** behaviour.

There is [an open RFC](https://github.com/KilianKilmister/rfcs/blob/latest/accepted/0000-peer-overrides.md) (**full disclosure, i'm the author of that particular RFC**), and discussions are currently ongoing

Here's the output:

```LOG
~/d/G/s/eslint-config-standard-with-typescript> npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: commitlint-config-awesome@1.0.4
npm ERR! Found: @commitlint/cli@9.1.2 at node_modules/@commitlint/cli
npm ERR!   for: dev dependency @commitlint/cli@"9.1.2"
npm ERR!   from: the root project
npm ERR! 
npm ERR! Could not add conflicting dependency: @commitlint/cli@8.3.5 at node_modules/@commitlint/cli
npm ERR!   for: peer dependency @commitlint/cli@"^7.0.0 || ^8.0.0"
npm ERR!   from: commitlint-config-awesome@1.0.4 at node_modules/commitlint-config-awesome
npm ERR!     for: dev dependency commitlint-config-awesome@"1.0.4"
npm ERR!     from: the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --legacy-peer-deps or --force
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Are you willing to submit a pull request to fix this bug?**

unlikely, as i'm not familiar with `commitlint`

**Comment by Divlo** [comment]
Thanks for your report! @KilianKilmister 
It should now be fixed since https://github.com/standard/eslint-config-standard-with-typescript/commit/b65731070575c23c28885cd63f9d19c5b43e1418.
