### ISSUE TITLE
Disallowing any kind of type-assertions on object literals can make typing unnescessarily cumbersome

### ISSUE THREAD

**Issue by KilianKilmister** [standard/eslint-config-standard-with-typescript#421]
What version of this package are you using?
"version": "19.0.1",

What operating system, Node.js, and npm version?

node-v14.9.0
npm-7.0.0-beta.9
macOS Catalina-v10.15.6

## Summary

Disallowing any type-assertions on object literals can make typing unnecessarily cumbersome in places where an excess property is desired. It could also encourage overuse of assertions in order to please the linter while actually decreasing type-safety

### Current Rule Definition

```JSON5
{
  '@typescript-eslint/consistent-type-assertions': [
    'error',
    {
      assertionStyle: 'as',
      objectLiteralTypeAssertions: 'never'
    }
  ]
}
```

### Suggested Change

```JSON5
{
  '@typescript-eslint/consistent-type-assertions': [
    'error',
    {
      assertionStyle: 'as',
      objectLiteralTypeAssertions: 'always'
    }
  ]
}
```

### Scenario: Parameter of type: object with a certain method

Many functions require an input of an object which has some kind of method. It is common to use an object literal for that parameter, and to get the correct `this-type` inside its methods a type assertion is practical and ensures a sufficient level of type-safety inside that objects methods

#### Given an **external** class `Bar` with a single construction parameter of type `Foo`:

```d.ts
export interface Foo {
  /** some kind of string transformation */
  method (param: string): string
}

export declare class Bar {
  constructor (arg: Foo)
}
```

#### Without any kind of assertions

```ts
/**
 * error TS2345: Argument of type '{ property: never[]; method(param: string):
 * string; }' is not assignable to parameter of type 'Foo'. Object literal may
 * only specify known properties, and 'property' does not exist in type 'Foo'.
 */
const exA = new Bar({
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string): string {
    this.property.push(param)
    return this.property.shift()
  }
})
```

#### The usual Fix, perfectly type-safe, proper `this`

```ts
/**
 * linter Error:
 * Always prefer const x: T = { ... }.
 * eslint@typescript-eslint/consistent-type-assertions)
 */
const exB = new Bar({
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    this.property.push(param)
    return this.property.shift()! // NOTE: '@typescript-eslint/no-non-null-assertion' will be topic of another issue
  }
} as Foo & {property: string[]})
```

#### Fixes which please the linter, but provide no other benefits over the previous example

```ts
const paramC = {
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    this.property.push(param)
    return this.property.shift()!
  }
}
const exC = new Bar(paramC)
```

```ts
const exD = new (Bar as new (arg: Foo & {property: string[]}) => Bar)({
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    this.property.push(param)
    return this.property.shift()!
  }
})
```

```ts
type BarConstructor = new <T extends Foo>(arg: T) => Bar // <-- how external definition should have looked like

const exE = new (Bar as BarConstructor)({
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    this.property.push(param)
    return this.property.shift()!
  }
})
```

#### Safe and simple fix, but if having to use it regularly defeats the purpose of having the rule enabled in the first place

```ts
// eslint-disable-next-line
const exG = new Bar({
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    this.property.push(param)
    return this.property.shift()!
  }
} as Foo & {property: string[]})
```

#### Unsafe fix but valid and very simple simple

```ts
const exH = new (Bar)({
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    (this.property as string[]).push(param)
    return (this.property as string[]).shift()!
  }
} as any)
```

### Why setting the rule to `objectLiteralTypeAssertions: allow-as-parameter` isn't enough

given object `Bar` with Property `Foo`

```d.ts
export interface Foo {
  /** some kind of string transformation */
  method (param: string): string
}

export declare const Bar: {
  param: Foo
}
```

#### Without any kind of assertions (same as above)

```ts
/**
 * error TS2345: Argument of type '{ property: never[]; method(param: string):
 * string; }' is not assignable to parameter of type 'Foo'. Object literal may
 * only specify known properties, and 'property' does not exist in type 'Foo'.
 */
bar.param = {
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    (this.property as string[]).push(param)
    return (this.property as string[]).shift()!
  }
}
```

#### The usual Fix, perfectly type-safe, proper `this` (same as above)

```ts
/**
 * linter Error:
 * Always prefer const x: T = { ... }.
 * eslint@typescript-eslint/consistent-type-assertions)
 */
bar.param = {
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    (this.property).push(param)
    return (this.property).shift()!
  }
} as Foo & {property: string[]}
```

#### Unsafe fix but valid and very simple simple (same as above)

```ts
bar.param = {
  property: ['some', 'kind', 'of', 'buffer', 'to', 'cycle'],
  method (param: string) {
    (this.property as string[]).push(param)
    return (this.property as string[]).shift()!
  }
} as any
```

## Larger issue

There are multiple builtins and node-native object affected by this rule for example the `Proxy` constructor or `fs.rmdirSync` the first is a complex object where various extra properties might make sense to exist and the latter is plainly typed wrong, lacking some properties in its `options` type which are used by the API. this also affects maps, sets and arrays which have been typed externally

Further more, this isn't uncommon in the ecosystem. Various types lack the necessary generic types params and it isn't always reasonable to include them, as they will take up a considerable amount of space, potentially causing confusion by how much information is thrown at somebody.

**Comment by mightyiam** [comment]
Hey, @KilianKilmister. Why don't you use `eslint-disable` comments where the rule doesn't apply well and otherwise enjoy it where it does?

**Comment by rostislav-simonik** [comment]
This seems like edge-case stuff, where it would be appropriate to use `eslint-disable`. We are going to close this, but if anybody disagrees please comment.
