### ISSUE TITLE
Lock peerDependency on eslint-plugin-standard to 4.x

### ISSUE THREAD

**Issue by feross** [standard/eslint-config-standard-with-typescript#479]
Until this package is updated for standard v16, it might be nice to lock the `peerDependency` on `eslint-plugin-standard` to 4.x since we have released 5.x which deprecates the plugin (which is no longer used in standard as of 16.0.0)

See: https://github.com/standard/standard/issues/1316#issuecomment-732146232

**Comment by Divlo** [comment]
We can close this issue, since we now updated the config for `standard@16`, thanks to #506. :tada:
