### ISSUE TITLE
Error: "This rule requires the `strictNullChecks` compiler option to be turned on to function correctly @typescript-eslint/strict-boolean-expressions"

### ISSUE THREAD

**Issue by ljonya** [standard/eslint-config-standard-with-typescript#481]
**Package version:** 19.0.1
**OS:** Kubuntu 20:10; **Node.js:** 14.10.0;  **npm:** 6.14.8

**What happened?**
I'm not sure if it's a bug, or if I might misunderstand something. [This](https://github.com/ljonya/ts-app.git) is minimal project to reproduce the problem. 
```sh
git clone https://github.com/ljonya/ts-app.git
cd ts-app
npm i
npx eslint ./test.ts 
```

Prints out an error:
```sh
/home/leonid/ts-app/test.ts
  0:1  error  This rule requires the `strictNullChecks` compiler option to be turned on to function correctly  @typescript-eslint/strict-boolean-expressions

✖ 1 problem (1 error, 0 warnings)
```
Although in `tsconfig.json` the property `strictNullChecks` is `true`.

**Comment by jtalcantara** [comment]
Same here, :(

**Node**: v14.15.0; **npm**: 6.14.8

**Comment by Divlo** [comment]
Same problem while working for https://github.com/standard/vscode-standardjs/.
Maybe related to this PR : https://github.com/typescript-eslint/typescript-eslint/pull/2345

**Comment by jtalcantara** [comment]
In my case, i'm using vscode, so I just had to reload the window and the problem was resolved.

**Comment by chantzlarge** [comment]
I'm also experiencing this issue, I've tried adding the various "strict*" options to `tslint.config` without success.

**Comment by juliancioc** [comment]
try to close and open the vscode :)

**Comment by LucasMallmann** [comment]
Always works :)

**Comment by adrianolangaro1** [comment]
Add "strictNullChecks": true to the "compilerOptions" object in tsconfig.json did the trick

**Comment by HenriqueOmena** [comment]
don't forget to reload your VsCode when u change  'strictNullChecks' to true to not receive this error message anymore

**Comment by Divlo** [comment]
As others said, please enable `strictNullChecks` in `tsconfig.json`.
Will close the issue for now, but please reopen if you have any doubt or others issues. :smile:

**Comment by VictorMeneghini** [comment]
> try to close and open the vscode :)

Best solution... Always works hahaha

**Comment by geraldoahnert** [comment]
> try to close and open the vscode :)

Thanks!

**Comment by JoanWilson** [comment]
> try to close and open the vscode :)

Thank you!! Best Solution

**Comment by lenodeoliveira** [comment]
@LucasMallmann 
Best solution!

**Comment by JayDouglass** [comment]
> Same problem while working for https://github.com/standard/vscode-standardjs/. Maybe related to this PR : [typescript-eslint/typescript-eslint#2345](https://github.com/typescript-eslint/typescript-eslint/pull/2345)
> 
> EDIT: I fixed it by explicitly setting `strict: true`, in the `tsconfig.json` of the root of the subfolders of typescript projects. Example for the vscode extension there are 2 subfolders : `client` and `server` and at the root there is a `tsconfig.json` with `strict: true`, but it wasn't enough, I also needed to set it in the `tsconfig.json` of the `client` and the `server` folders. Hopefully I'm clear and it's helping to find out how to solve the issue.

I had a similar problem in a new Vite/React/TS project. I had to set `strict: true` in `tsconfig.node.json`.
