### ISSUE TITLE
no-type-alias could be helpful

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#56]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-type-alias.md

**Comment by swansontec** [comment]
After reading the docs for that, as well as the other rules in this repo, I would configure `no-type-alias` like this:

```javascript
{
  // Enables things that are difficult to achieve in other ways:
  allowAliases: 'in-unions-and-intersections',
  allowLiterals: 'in-unions-and-intersections',
  allowMappedTypes: 'in-unions-and-intersections',

  // The `prefer-function-type` rule forces this:
  allowCallbacks: 'always'
}
```

**Comment by mightyiam** [comment]
@swansontec, I read the rule doc and I agree with the options suggested by you.

**Comment by LinusU** [comment]
I use case I've ran into lately is:

```typescript
import firebase = require('firebase')

type DocumentReference = firebase.firestore.DocumentReference

// ...

function foo(ref: DocumentReference) {
  // ...
}
```

**Comment by swansontec** [comment]
@LinusU That's a valid point! Shortening long names might also be a valid use-case.

The `@typescript-eslint/prefer-function-type` and `@typescript-eslint/prefer-interface` rules already get rid of the most "wrong" uses of the `type` keyword, so the remaining cases would be things like intersections, unions, or your example shortening long names. In that case, maybe `no-type-alias` doesn't give much additional benefit?

The main benefit I can see would be banning "useless" type aliases like `type Username = string`. It's too bad there is no `@typescript-eslint/no-useless-type` rule, or at least an option to the `allowAliases` configuration that would trivial cases like this.

**Comment by mightyiam** [comment]
Shortening a nested type does seem like a constructive pattern. Isn't there another way to get a reference to that nested type other than with a type alias? And... did you check that this is an error according to this rule? It seems like it would be, always. I'm closing this on the count of @LinusU's shortening example. If anyone has an idea, please reopen.

**Comment by LinusU** [comment]
> Shortening a nested type does seem like a constructive pattern. Isn't there another way to get a reference to that nested type other than with a type alias?

I would love to know this as well! ☺️
