### ISSUE TITLE
Dependency conflict when upgrading eslint-plugin-promise to 5.1.0

### ISSUE THREAD

**Issue by martinburger** [standard/eslint-config-standard-with-typescript#579]
**What version of this package are you using?**

`20.0.0`

**What operating system, Node.js, and npm version?**

```
❯ uname -v
Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64
❯ node --version
v16.2.0
❯ npm --version
7.13.0
```

**What happened?**

I want to upgrade `eslint-plugin-promise` from `4.3.1` to `5.1.0`.

However, this results in unresolvable dependencies:

```
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: eslint-plugin-promise@5.1.0
npm ERR! node_modules/eslint-plugin-promise
npm ERR!   dev eslint-plugin-promise@"^5.1.0" from the root project
npm ERR!   peer eslint-plugin-promise@">=4.2.1" from eslint-config-standard-with-typescript@20.0.0
npm ERR!   node_modules/eslint-config-standard-with-typescript
npm ERR!     dev eslint-config-standard-with-typescript@"^20.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-promise@"^4.2.1" from eslint-config-standard@16.0.2
npm ERR! node_modules/eslint-config-standard
npm ERR!   eslint-config-standard@"^16.0.0" from eslint-config-standard-with-typescript@20.0.0
npm ERR!   node_modules/eslint-config-standard-with-typescript
npm ERR!     dev eslint-config-standard-with-typescript@"^20.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/$USER/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/$USER/.npm/_logs/2021-05-26T09_36_26_360Z-debug.log
```

**What did you expect to happen?**

I would like to upgrade `eslint-plugin-promise` to that latest version without running into above issue.

Note, this might be related to https://github.com/standard/eslint-config-standard/issues/184 and #557.

**Comment by martinburger** [comment]
I don't know if the following changes are sufficient and/or if both are required to fix this issue, but it might help investigate it:

- Update `eslint-config-standard` from `16.0.0` to `16.0.3`
- Change peer dependency version of `eslint-plugin-promise` from `>=4.2.1` to `^4.2.1 || ^5.0.0`

The first change might be sufficient.

**Comment by martinburger** [comment]
FYI: It seems that #557 has been fixed already in `master`.

At least, if I clone this repository I can update `eslint-plugin-promise` to `5.1.0` and run `npm install` without encountering the issue in #557.

Thus, "just" releasing a new version should fix this issue.

**Comment by mightyiam** [comment]
Should be fixed by #602.

**Comment by lygstate** [comment]
request for release new version of eslint-config-standard-with-typescript

**Comment by martinburger** [comment]
Are there any plans to release a new version to fix this issue?
