### ISSUE TITLE
Some upstream standard rules are not properly propagated to their @typescript-eslint version

### ISSUE THREAD

**Issue by 6XGate** [standard/eslint-config-standard-with-typescript#582]
**What version of this package are you using?** `20.0.0`

**What operating system, Node.js, and npm version?** `node v12.22.1` `npm v7.14.0`

**What happened?**
The following rules are defined in the upstream **standard** configuration but not propagated to their `@typescript-eslint` equivalents.
- `comma-dangle`
- `no-loss-of-precision`
- `no-implied-eval`
- `no-loss-of-precision`
- `object-curly-spacing`
- `space-infix-ops`

**What did you expect to happen?**
That the listed rules would be propagated to their TypeScript version and disabled.

**Are you willing to submit a pull request to fix this bug?**
maybe

**Comment by 6XGate** [comment]
@rsdmike, camelcase isn't part of the TypeScript ESLint rules. It's equivalent is naming-convention.

**Comment by mightyiam** [comment]
By the way, @rostislav-simonik and I are currently working on this.

**Comment by 6XGate** [comment]
@mightyiam, I've got a much more complete form of my original PR's intension in scalecore/eslint-config-scalecore which handles propagation, conversion, and exclusion of rules enabled by eslint-config-standard, or any other configuration.
It's `develop` branch is even more complete.

**Comment by mightyiam** [comment]
@6XGate I have a feeling that @rostislav-simonik and I doing this ourselves would end up being an effort similar to reading your code and trying to adapt it to our purpose. Or perhaps less of an effort, due to reduced context in comparison.

Another option is for you to join us in our mob programming sessions. Three is a real mob.

**Comment by 6XGate** [comment]
I could try tackling that Monday after I'm back home.

**Comment by 6XGate** [comment]
I just pushed an update to the #583 pull request that should propagate all rules `@typescript-eslint` indicates are extension or replacement rules.
