### ISSUE TITLE
Rule default-param-last enforced, contradicting eslint-standard

### ISSUE THREAD

**Issue by paperrin** [standard/eslint-config-standard-with-typescript#589]
**What version of this package are you using?**
using ts-standard 10.0.0
which is using 20.0.0 of this package

**What operating system, Node.js, and npm version?**
Windows 10
Node 14.15.1
NPM 7.5.2

**What happened?**
This rule is enforced
```
'@typescript-eslint/default-param-last': 'error'
```

**What did you expect to happen?**
Expected rule to be relaxed like it was on https://github.com/standard/eslint-config-standard/commit/25a0d26dff95aa131cdd85bf6fec7efba31fefcf

**Are you willing to submit a pull request to fix this bug?**
Would be my first contribution to open source, of course I would.

**Comment by Divlo** [comment]
Thanks for your report! @paperrin 

@mightyiam Do you think it is viable to disable this rule as `standard` did ?

**Comment by mightyiam** [comment]
Yes, consistency with standard is desirable.
