### ISSUE TITLE
CI no longer running

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#598]
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by Divlo** [comment]
We should probably reconsider these PRs:
- #530 
- #533

**Comment by voxpelli** [comment]
Agree, GitHub Actions would be a good way forward, I move semistandard to that the other day

**Comment by mightyiam** [comment]
I would not like to lose the automation of Travis bumping Node.js versions:
https://github.com/standard/eslint-config-standard-with-typescript/pull/530#discussion_r582633766

**Comment by voxpelli** [comment]
@mightyiam And you are aware of the limitations that Travis now sets on opensource projects? See eg. https://ropensci.org/blog/2020/11/19/moving-away-travis/ and https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing – in summary:

> no longer has a generous free tier for open-source projects

So while the Renovate integration is nice, question is whether that niceness offsets the downsides of TravisCI.com and whether it's easier to work around one or the other?

(That and the fact that GH Actions can be activated right away, whereas Travis CI seems to be less than easy to add)

**Comment by voxpelli** [comment]
One way in which GitHub Actions are improving in the versioning regard is that newly released Node action contain eg a `lts/*` alias that can be used to always target latest LTS release: https://github.com/actions/setup-node/releases/tag/v2.2.0

**Comment by voxpelli** [comment]
And here's an issue about also supporting a `latest`: https://github.com/actions/setup-node/issues/257

**Comment by Divlo** [comment]
Thanks for the information!
I reopened the PR: #530

**Comment by mightyiam** [comment]
It seems reasonable to eventually move to GitHub Actions. Yet, before doing that, could we please enable Travis CI again. We would see how much of the reduced free open source offering we use and whether that is an issue or not.

**Comment by mightyiam** [comment]
> And here's an issue about also supporting a `latest`: [actions/setup-node#257](https://github.com/actions/setup-node/issues/257)

Yes, this seems to potentially be able to replace renovate's role in CI.

**Comment by mightyiam** [comment]
It's running. Let's see how long the credits last.
