### ISSUE TITLE
please consider releasing a new version. 

### ISSUE THREAD

**Issue by AntonioMeireles** [standard/eslint-config-standard-with-typescript#645]
latest published one from January... 

Thanks in advance and keep the great work!

**Comment by mightyiam** [comment]
Will do.

**Comment by mightyiam** [comment]
I promise I'll get to this.

**Comment by mightyiam** [comment]
I tagged a new version and then came across a bug that fails the `npm publish` command. Will look into it.

**Comment by mightyiam** [comment]
`v21.0.1` is out. Hope I didn't break anything.

**Comment by AntonioMeireles** [comment]
**THANK YOU** for your patience and hard work!. 

will report back if issues arise, 

All the best,
