### ISSUE TITLE
mightyiam is stepping down

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#727]
I'm going to turn off 'watching' for the project, because I don't actively maintain it. If anyone would like advice, feel free to mention me.

**Comment by sQVe** [comment]
👋

Who is going to actively maintain this? Looking at the commit history it seems like you've been the most active lately @mightyiam.

Are `standard` looking for maintainers for this?

**Comment by Divlo** [comment]
Thanks for your work on this repo. @mightyiam 

I could try to maintain it, with others StandardJS members.

The next improvement of this package is to support ESLint v8, it will be possible when `eslint-config-standard` also support this.

**Comment by sQVe** [comment]
I'm open to jumping in if needed. I use this project daily and I'm very comfortable with the ESLint ecosystem + TypeScript.

I dunno what the process is to join the
`standard` org - but that is for another time, I guess 😊🤷‍♂️

**Comment by Divlo** [comment]
> I'm open to jumping in if needed. I use this project daily and I'm very comfortable with the ESLint ecosystem + TypeScript.
> 
> I dunno what the process is to join the `standard` org - but that is for another time, I guess blushman_shrugging

Happy to hear that! :heart: @sQVe 
Feel free to open PRs, create issues, or answer already opened issues.

Would love, if you could already investigate what is needed to support `eslint@8` if you wanna contribute. :smile:

**Comment by LinusU** [comment]
Thank you for your work @mightyiam ❤️

**Comment by mightyiam** [comment]
I'm willing to help anyone understand the reasoning, the tests, the process, etc. In short, to mentor. Even live on a call. I do a lot of mob programming so I'm not shy about this kind of activity.

**Comment by voxpelli** [comment]
Oh, I had forgotten / not seen this, my preference would be that we would tie this closer to the other core Standard modules and streamline the releases that way, keeping a shared set of maintainers across the organization.

For now I could for sure help out with releasing and such

**Comment by meyfa** [comment]
> my preference would be that we would tie this closer to the other core Standard modules and streamline the releases that way

That seems like a great idea, given that TypeScript is, for many projects, not an afterthought but the primary mode of development and we should ensure this config holds up to that. Still that's maybe more of a long-term goal, IMHO. Right now I'd prioritize getting this shipped through whatever method works.

> For now I could for sure help out with releasing and such

Thank you! I haven't seen any opposition to a release from a technical standpoint, so perhaps you could do the release?
Of course my offer still stands to help out as well, but I would hazard a guess that releasing is quicker than getting new people up-to-speed. It's your choice, though :)

**Comment by DiegoRBaquero** [comment]
> Oh, I had forgotten / not seen this, my preference would be that we would tie this closer to the other core Standard modules and streamline the releases that way, keeping a shared set of maintainers across the organization.
> 
> For now I could for sure help out with releasing and such

Could you release latest manually for now?

How would you like to streamline the releases? Any way I can help?

**Comment by mightyiam** [comment]
I can see that this project needs some more love. It's difficult to see that lack of maintenance. If anyone wants to pair with me on this, schedule here: https://calendly.com/mightyiam

**Comment by mightyiam** [comment]
Several have approached me but then none followed through.

**Comment by mightyiam** [comment]
A session with @rostislav-simonik and I has been scheduled to move this project forward. It would take more than that session to make significant progress, but it's better than nothing and I appreciate the effort.

**Comment by mightyiam** [comment]
Made some progress. Another session scheduled.

**Comment by voxpelli** [comment]
@mightyiam Shall I interpret this as that eg. me and @Divlo shouldn't be doing anything with this repo for now?

Any way we could involve us all in this?

**Comment by mightyiam** [comment]
> @mightyiam Shall I interpret this as that eg. me and @Divlo shouldn't be doing anything with this repo for now?
> 
> Any way we could involve us all in this?

I can imagine you joining us. We're working in mob programming format.
