### ISSUE TITLE
Support ESLint 8

### ISSUE THREAD

**Issue by sQVe** [standard/eslint-config-standard-with-typescript#728]
⭐ Support ESLint 8.

This is a **tracking issue** for supporting `eslint@8`. It's currently being blocked by:

- [x] `typescript-eslint` ([now supports `eslint@8`](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0))
- [x] `eslint-config-standard` (https://github.com/standard/eslint-config-standard/pull/193)

---

New `eslint` rules with `typescript-eslint` equivalents:
- [no-loss-of-precision](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-loss-of-precision.md)

New rules worth considering:
- [no-unnecessary-type-constraint](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-type-constraint.md)
- [no-unsafe-argument](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unsafe-argument.md)

---

Refs: 
- [Changes to the recommended sets for 5.0.0](https://github.com/typescript-eslint/typescript-eslint/issues/3746)

**Comment by sQVe** [comment]
I didn't have time going through all entries of what `typescript-eslint` actually recommends in their `recommended` config. My gut tells me that it might be worth giving it a glance though - there might be some useful rules that we've missed.

**Comment by meyfa** [comment]
https://github.com/standard/eslint-config-standard/pull/193 has been merged. What does the process look like for this issue here, and is there some way to help?

**Comment by xCykrix** [comment]
Would definitely like some news on getting this merged so I can update my toolchain. Is there anything that could be assisted with to get this rolling @sQVe ?

**Comment by sQVe** [comment]
@xCykrix The first thing we would need to resolve is to update the dependencies for `eslint@8`. After that I feel think it would be great to have some consideration on the new rules that we could add.

**Comment by Divlo** [comment]
We wil add support for ESLint v8, when `eslint-config-standard` v17 has been released stable.

**Comment by sQVe** [comment]
@Divlo Until then it might make sense to have a discussion about the rules that applies only for TypeScript land?

**Comment by Divlo** [comment]
Sure we can! @sQVe

Maybe in different issues to make it more maintainable.

**Comment by ghaiklor-wix** [comment]
@sQVe maybe you could make a `next` release that includes the `next` version of `eslint-config-standard`? So we could start testing it out and reporting any issues 🙏

**Comment by linonetwo** [comment]
When `npm i -D eslint-config-standard@next`

Could not resolve dependency:
npm ERR! peer @typescript-eslint/eslint-plugin@"^4.0.1" from eslint-config-standard-with-typescript@21.0.1

this means `eslint-config-standard-with-typescript` need to update  deps to come up with `eslint-config-standard@next`
