### ISSUE TITLE
ESLint couldn't find the plugin "eslint-plugin-eslint-plugin".

### ISSUE THREAD

**Issue by HomyeeKing** [standard/eslint-config-standard-with-typescript#787]
**What version of this package are you using?**
21.0.1
**What operating system, Node.js, and npm version?**
osx , 
node: 14.19.0
npm: 8.5.4
**What happened?**
here's my config:

```json
// .eslintrc.json
{
  "extends": ["standard-with-typescript"]
}
```
when run `eslint .`, throw error

![image](https://user-images.githubusercontent.com/49113249/159477644-94cee760-0956-42c1-a882-110e2d4bd734.png)

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**
no idea, but I found that some packages in `@typescript-eslint/eslint-plugin` uses `eslint-plugin-eslint-plugin`:

https://github.com/typescript-eslint/typescript-eslint/blob/9707daa482bd11f1eb813710347fb76db8bd8353/packages/website/.eslintrc.js#L3

https://github.com/typescript-eslint/typescript-eslint/blob/9707daa482bd11f1eb813710347fb76db8bd8353/.eslintrc.js#L4

**Comment by HomyeeKing** [comment]
@mightyiam  please check this issue

**Comment by mightyiam** [comment]
Thank you for reaching out, @HomyeeKing. To help I would need a minimal reproduction. Until then, closing.

**Comment by HomyeeKing** [comment]
@mightyiam  https://github.com/HomyeeKing/repo-eslint-plugin/tree/master

**Comment by HomyeeKing** [comment]
@mightyiam  how about this issue

**Comment by mightyiam** [comment]
Sorry. I'll get to it.

**Comment by mightyiam** [comment]
I'm not sure what pnpm may be doing funny. I didn't try your reproduction with pnpm. I tried with npm and it seems to work.

**Comment by mightyiam** [comment]
There is no such plugin as far as I remember. Try to find where that is coming from.

**Comment by HomyeeKing** [comment]
@mightyiam  OMG, after debugging all day long, I finally found the cause that there's an .eslintrc.js at the parent dir(I have no idea when I create this 😕)...

## Reason
>ESLint will automatically look for them in the directory of the file to be linted, and in successive parent directories all the way up to the root directory of the filesystem (/), the home directory of the current user (~/), or when root: true 
in other words   ------- [reference](https://eslint.org/docs/user-guide/configuring/configuration-files#using-configuration-files)

that explains why `eslint` will read the parent config file unless you set `root: true` in your config file or making sure don't have any config file in your acestors

## Explain

### structure
```
|-a
  |--- .eslintrc.js
  |--- b
       |--- .eslintrc.json

```
```js
// cwd: /a/b
npx eslint .
```
in this case, the output will be an error like:
> plugin not found in`/a`  from the config file `'../.eslintrc.js'` _(this confuse me for a long time why `/a`  and `.eslintrc.js`😢)_

now everything seems clear for me

Thanks for your time❤️!
