### ISSUE TITLE
Please cut a release to allow using the latest @typescript-eslint/eslint-plugin

### ISSUE THREAD

**Issue by dead-claudia** [standard/eslint-config-standard-with-typescript#792]
I'm on 21.0.1 (the latest version) but am impacted by https://github.com/typescript-eslint/typescript-eslint/issues/3727, fixed in https://github.com/typescript-eslint/typescript-eslint/commit/d97140ecf4aeb0a1f8b391f46a31881f21ad93c3 and out for 5 months. I also see https://github.com/standard/eslint-config-standard-with-typescript/pull/702 has the fix I need, but that update has not yet been released.

Please cut a release so I can remove some `eslint-ignore`s related to that issue.

**Comment by Divlo** [comment]
> @Divlo Could you release a new version ?

@QuentinFarizon I don't have the permissions/rights to publish a new version on npm for this package.
Hopefully, @mightyiam might have some time soon to publish a new version.

**Comment by ChristopherChudzicki** [comment]
@Divlo A version on NPM would definitely be better, but what would you think of creating a branch in this repo with
- new package version (probably major version 22.0.0 since I ESLInt 7 has been dropped as a peer depenency?)
- lib directory NOT git-ignored

That would enable installing the repo via package.json:
```
    eslint-config-standard-with-typescript: "git+https://github.com/standard/eslint-config-standard-with-typescript.git#v22.0.0"
```

Or as a workaround for other people, that's what I've done with https://github.com/ChristopherChudzicki/eslint-config-standard-with-typescript/releases/tag/v22.0.0 (Though, having it on the main repo seems better which is why I'm suggesting it).

**Comment by mightyiam** [comment]
I won't get to this. If anyone wishes to take over contact me directly.

**Comment by tomasstrejcek** [comment]
What is required to move this forward? maybe @Divlo can help? As I am not a contributor I can only offer my future support to whoever will try to get this done :)

**Comment by mightyiam** [comment]
> I'm happy to take over @mightyiam @feross 

@meyfa also offered the same.

**Comment by voxpelli** [comment]
If @mightyiam doesn't want to continue to maintain these modules, then I would prefer that we align them with the other modules in this org and try to streamline the release progress and get a more synced up release progress with less duplicate work.

Not sure if that's what @mightyiam is saying though?

**Comment by mightyiam** [comment]
Continue discussion in #727 ?

**Comment by mightyiam** [comment]
Work on the project is ongoing on a weekly schedule. A release will be cut eventually. See #840 .

**Comment by paralin** [comment]
It's on a weekly schedule but it's been months :)

**Comment by mightyiam** [comment]
@paralin yup. The blocker currently is that I'm not an owner of this organization. A GitHub App needs to be created to serve as part of the implementation of #840 . It seems only organization owners can do that. I'm sure this will be resolved one way or another soon.

**Comment by lusu007** [comment]
Can't a manual release be made one very last time? The release blocks tens of projects for months....

In my opinion #840 could be worked on after a release.

**Comment by mightyiam** [comment]
Yes, that's correct, @lusu007 . But... as soon as I get the permission I can launch the CD pipeline. I already managed to get a response from someone who technically can do that. But they referred me to @feross :shrug:

**Comment by lusu007** [comment]
It's been almost 2 weeks since the last sign of life. Did you get the permissions to launch the CD pipeline? @feross are you able to speed up the whole thing?

Nevertheless, I think at the moment everyone would love a manual release. The lack of a release, unlike the CD pipeline, costs many projects real money as a lot of time has to be invested in implementing alternatives.

**Comment by mightyiam** [comment]
I've contacted several of the owners of this organization asking them to either grant me greater permissions in the standard organization or create the GitHub app themselves. Either no response or "I don't feel comfortable doing either of those".

So just now I've contacted two more of the owners.

It's funny that you mention money, @lusu007 . I don't see any. And yet I do desire to serve the users best I can. I told myself that the next release will be an automated one. Shall I regress from that for the benefit of the users and make a manual release?

**Comment by mightyiam** [comment]
https://www.npmjs.com/package/eslint-config-standard-with-typescript/v/22.0.0

**Comment by martinburger** [comment]
@mightyiam Thank you for your great and tireless efforts.

**Comment by sebastianrothe** [comment]
> https://www.npmjs.com/package/eslint-config-standard-with-typescript/v/22.0.0

Works perfectly.
