### ISSUE TITLE
Dependencies different from standard

### ISSUE THREAD

**Issue by despian** [standard/eslint-config-standard-with-typescript#80]
Thanks for this package. Hopefully, they will merge these rules.

Why are the packages required to run this listed as peer dependencies instead of normal dependencies? `standard` just has them listed like this: [standard/package.json#L14-L22](https://github.com/standard/standard/blob/155d52710f587439d58b146f790df322336e195a/package.json#L14-L22)

Also is there a reason that the version requirements are different to the ones standard are using or is just that you're using greenkeeper? It has caused some problems running regression tests against node v6. Namely using version 9 of `eslint-plugin-node` instead of 7 breaks compatibility with node 6.

**Comment by mightyiam** [comment]
Thank you for the interest, @despian.

Regarding merging of these rules, there's no intention to merge this into the core Standard rules. There is, however:

1. Intention for this repo to [join the Standard family officially](https://github.com/standard/standard/issues/1007), as you've commented on.
2. [A proposal for official extensions for Standard](https://github.com/standard/standard/pull/703), which could be a way to more easily use these rules.

> Why are the packages required to run this listed as peer dependencies instead of normal dependencies? 

This package is not equivalent to https://www.npmjs.com/package/standard. It is equivalent to https://www.npmjs.com/package/eslint-config-standard, which also has the other rules as peerDependencies:

https://github.com/standard/eslint-config-standard/blob/f7d50e01310866458fd844625cf588d4ee39823b/package.json#L50-L56.

This should change. See this RFC: https://github.com/eslint/rfcs/pull/5

> Also is there a reason that the version requirements are different to the ones standard are using or is just that you're using greenkeeper?

It does make sense to keep in sync with standard's dependencies actually. I haven't thought of that.

> It has caused some problems running regression tests against node v6.

Node.js v6 had reached end-of-life in April. While I did not intentionally de-sync peerDependencies with eslint-config-standard, I don't feel comfortable with downgrading for the purpose of supporting an end-of-life Node.js version. And eslint-config-standard should soon follow in dropping Node.js v6. ESLint v6 already dropped support for Node.js v6.

Are you sure you need Node.js v6 support?

**Comment by despian** [comment]
I see, thanks for the clarification.

I'm not personally interested in node 6 but a project I've been contributing to @fastify still runs tests against it.

**Comment by mightyiam** [comment]
@despian sounds like a reasonable workaround.

**Comment by mightyiam** [comment]
Actually, I'm going to leave this open and say that this is blocked by https://github.com/eslint/eslint/issues/3458 and also Standard adopting the implementation by having its plugins as regular dependencies.

**Comment by mightyiam** [comment]
Splitting #97 out of this.
