### ISSUE TITLE
(Upstream) [no-redeclare] error for declare namespace

### ISSUE THREAD

**Issue by despian** [standard/eslint-config-standard-with-typescript#81]
Using the [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) feature of TypeScript causes the `no-redeclare` rule to be triggered.

E.g.
```ts
declare namespace Foo {
...
}
declare const Foo: Bar
```

I couldn't find a rule upstream in `typescript-eslint`. Maybe it needs to be fixed there first. I'll create an issue there too.

Edit:
~~Found an existing issue: [typescript-eslint#60](https://github.com/typescript-eslint/typescript-eslint/issues/60)~~

Edit: upstream issue merged into https://github.com/typescript-eslint/typescript-eslint/issues/1856

**Comment by mightyiam** [comment]
Thank you for following through to upstream. I would [work around using comments](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments). Closing here.

**Comment by despian** [comment]
Yeah, I'm already using comments.

I'm guessing that the fix upstream will result in a new rule. Once available won't the standard rule need to be disabled and the new rule enabled in this project? Do you think it's worth keeping this issue open to keep track of that piece of work?

**Comment by mightyiam** [comment]
Sure, we could keep it open. I'll rename it.

**Comment by rostislav-simonik** [comment]
it seems to have been closed upstream.
