### ISSUE TITLE
The version 21.0.1 peerDependencies is not update

### ISSUE THREAD

**Issue by likun7981** [standard/eslint-config-standard-with-typescript#831]
https://github.com/standard/eslint-config-standard-with-typescript/blob/v21.0.1/package.json#L59

**Comment by likun7981** [comment]
Although the source code is updated, the release tag is not updated

**Comment by Mulando** [comment]
This needs a new release tag because of dependency updates. Else projects using this and eslint v8 and node v16 break without forcing installs.

**Comment by mightyiam** [comment]
Work on this repo is actually on a weekly schedule. Solutions will come, hopefully.

**Comment by paralin** [comment]
I hope someone releases a new version soon!

**Comment by mightyiam** [comment]
@paralin #840 is nearly ready. From then on you'll probably get releases more rapidly than you would have liked :sweat_smile:

**Comment by mightyiam** [comment]
Obsolete.
