### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#840]
One of the causes for burnout is repetitive tasks that should be automated away. I made too many manual releases for this project. The next release coming out of this project as far as I'm concerned will be triggered by a workflow on push/merge to the `master` branch.

**Comment by mightyiam** [comment]
@fcole90 me and @rostislav-simonik are pairing on a weekly schedule on this. If the schedule happens to fit you, we could mob. I have a lot of experience mob programming, as I am the founder of @mobusoperandi.

**Comment by mightyiam** [comment]
@voxpelli I would like to decouple as much as possible from platform specific features. Especially proprietary ones. Using that release-please GitHub action would mean exactly that.

**Comment by voxpelli** [comment]
@mightyiam Which "platform specific" features are you talking about here?

Seems to me like [both semantic-release](https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions) and [release-please-action are](https://github.com/google-github-actions/release-please-action) implemented through GitHub Action workflows?

Neither are proprietary and neither needs any app to be installed to the organization?

**Comment by mightyiam** [comment]
The platform specific features I'm referring to are GitHub Actions. That release-please-action is a GitHub Actions action. semantic-release is not. If we were to migrate to another CI provider, it would be less work had we chosen semantic-release. This is classic vendor lock-in avoidance.

**Comment by voxpelli** [comment]
Both are based on conventional commit formatted commit messages, so swapping them out for something else is very simple.

+ release-please isn’t a GH Action at its core: https://github.com/googleapis/release-please

It’s only a vendor lock-in if we can’t easily move away from it. That’s easy with both.

**Comment by mightyiam** [comment]
CD is mostly implemented. Just missing a GitHub app for the purpose of bypassing required PR branch protection. I've done this twice before in different projects. I require the greater permission (owner?) on the @standard organization to create and install the app. @standard/team if anyone can give me the permission, please...

**Comment by voxpelli** [comment]
@mightyiam Can you link to what CD setup you have opted for? And what app it is that you need?

**Comment by voxpelli** [comment]
Right, so what you want to do is this? https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-a-master-branch

And there they say:

> **Note:** Automatically populated `GITHUB_TOKEN` cannot be used if branch protection is enabled for the target branch. It **is** not advised to mitigate this limitation by overriding an automatically populated `GITHUB_TOKEN` variable with a Personal Access Tokens, as it poses a security risk.

And you're right, `mob/cd` looks to be the correct branch. Here's a comparison link for others who are following along: https://github.com/standard/eslint-config-standard-with-typescript/compare/mob/cd

I would suggest making a draft PR of that branch and link that PR to this issue. That way we can talk more hands on about what needs to be done, which would be more helpful.

**Comment by voxpelli** [comment]
An alternative solution as I see it is to use [`release-please-action`](https://github.com/google-github-actions/release-please-action) as it rather than pushes to the protected branch opens a PR against it, which can then be reviewed and merged normally.

When merged `release-please-action` creates a release for the project, something which is outside branch protection rules, and it allows for [publishing to npm](https://github.com/google-github-actions/release-please-action#automating-publication-to-npm) as well.

**Comment by voxpelli** [comment]
I would also suggest looking into https://commitlint.js.org/ as that enables tools like https://github.com/vivaxy/vscode-conventional-commits to be used in authoring commits

**Comment by mightyiam** [comment]
The release-please workflow — I don't like it. It takes merging a PR to have a release. I'd like more automation, where I have to do nothing and releases just occur from pushes to `master`.

We already have commit linting in place. That's important for such a workflow.

[Here's a project I'm involved with which has a CD setup similar to what I'm trying to achieve here](https://github.com/mobusoperandi/michie/blob/62bf6afa5aba3ade8813ec2d3563028df035528e/.github/workflows/ci.yml).

The only thing I'm missing is the GitHub App created and installed and the app ID and token as secrets in the repo.

**Comment by mightyiam** [comment]
Whether a release occurs depends on commit messages since last release. For example, typically, the types `feat/fix/perf` and possibly `doc` and anything with a `BREAKING CHANGE: ...` triggers a version bump while `chore/test/build/refactor` do not.

Automatic releases takes the drama away from them. Who cares how many releases are made as long as they all explain themselves with nice changelog entries?

Users don't typically complain about frequency of releases — they complain about frequency of breaking releases.

**Comment by meyfa** [comment]
> It takes merging a PR to have a release.

Since whichever tool is chosen does not also review PRs, merging a PR will always be required for a release to happen. There's no way to get around some amount of manual work. In fact, the amount of work needed might be reduced with release-please since there's an additional safety net and hence less upfront work on each PR is required.

> Users don't typically complain about frequency of releases — they complain about frequency of breaking releases.

A Renovate Bot config rule will have to be added for consumers of this package if releases happen so often, to cut down email spam through GitHub notifications. (Arguably still better than no releases, though.) Re number of breaking releases: release-please would allow bundling of multiple breaking changes into a single release, which seems difficult to achieve with semantic-release.

**Comment by voxpelli** [comment]
> Re number of breaking releases: release-please would allow bundling of multiple breaking changes into a single release, which seems difficult to achieve with semantic-release.

Indeed, and would enable manual pre-releases for such breaking changes, like we did with [`standard-engine@15.0.0-0`](https://github.com/standard/standard-engine/releases/tag/v15.0.0-0) and [`eslint-config-standard@17.0.0-0`](https://github.com/standard/eslint-config-standard/releases/tag/v17.0.0-0)

I find that helpful in verifying releases in the wider ecosystem, enabling eg. myself to start trying them out in my own projects and verifying them there, before pushing the new major to the wider community.
