### ISSUE TITLE
[no-object-literal-type-assertion] allowAsParameter

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#89]
```ts
const foo = [['a', 1], ['b', 2]].reduce(
  (o, [k, v]) => {
    o[k] = v + 1
    return o
  },
  {} as Record<string, number> // eslint-disable-line @typescript-eslint/no-object-literal-type-assertion
)
```

I see nothing wrong with that assertion. Perhaps `allowAsParameters` should be turned on.

**Comment by mightyiam** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-object-literal-type-assertion.md

**Comment by LinusU** [comment]
I think it wants you to type:

```diff
-const foo = [['a', 1], ['b', 2]].reduce(
+const foo: Record<string, number> = [['a', 1], ['b', 2]].reduce(
   (o, [k, v]) => {
     o[k] = v + 1
     return o
   },
-  {} as Record<string, number> // eslint-disable-line @typescript-eslint/no-object-literal-type-assertion
+  {}
 )
```

Not sure that it's nice to enforce that though, but maybe it is... 🤔

**Comment by mightyiam** [comment]
I would be alright with that. How did you figure this out?

**Comment by LinusU** [comment]
> How did you figure this out?

I just guessed from the rule description, I haven't tested it 😄

**Comment by toddbluhm** [comment]
I think the current way is good. Another solution for this is:
```diff
const foo = [['a', 1], ['b', 2]].reduce(
-  (o, [k, v]) => {
+  (o: Record<string, number>, [k, v]) => {
    o[k] = v + 1
    return o
  },
-  {} as Record<string, number> // eslint-disable-line @typescript-eslint/no-object-literal-type-assertion
+ {}
)
```

You are probably good to close this out, and someone can reopen/comment on this if they have a differing opinion 😄
