### ISSUE TITLE
remove `@typescript-eslint/indent` rule

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [standard/eslint-config-standard-with-typescript#978]
**What version of this package are you using?**

23.0.0

Rules set contains the `@typescript-eslint/indent` rule (https://github.com/standard/eslint-config-standard-with-typescript/blob/master/src/index.ts#L9 + https://github.com/standard/eslint-config-standard-with-typescript/blob/master/src/index.ts#L63) which is [broken](https://github.com/typescript-eslint/typescript-eslint/issues/1824)

Maybe it's a good idea to remove it, as using this config without manual tweaking might be annoying (otherwise it's pretty cool config, thanks for your work!)

**Comment by LinusU** [comment]
Interesting, I've never seen this myself and we using this in several large code bases 🤔 

There is also a work around posted that maybe we could use?

```json
        "@typescript-eslint/indent": [
          "error",
          2,
          {
            "ignoredNodes": [
              "PropertyDefinition[decorators]",
              "TSUnionType",
              "TSTypeParameterInstantiation",
              "TSIntersectionType"
            ]
          }
        ],
```

**Comment by jacekkarczmarczyk** [comment]
Yeah, this workaround might work. I wonder though how you've never encountered any problems with this rule, I've noticed it straight away after I started using config from this repo :)

**Comment by LinusU** [comment]
Hehe, interesting, could you give an example that fails?

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/200546447-38b87b12-9e95-4cf5-af8d-ca4e4f291a4e.png)

In my project I've seen this one <https://github.com/typescript-eslint/typescript-eslint/issues/455>, but probably others too

**Comment by mightyiam** [comment]
Removing this rule doesn't seem reasonable, because it's one of the primary style rules.

By the way, whether style rules are appropriate in Standard in light of the increasing popularity of deterministic formatters such as Prettier, is a different conversation.

Regarding a possible workaround, we need some concrete examples in order to consider it. If you care enough, please provide those.

Otherwise, we'll close this issue with this comment. Feel free to comment if you still disagree.

**Comment by LinusU** [comment]
> By the way, whether style rules are appropriate in Standard in light of the increasing popularity of deterministic formatters such as Prettier, is a different conversation.

e.g. being discussed here https://github.com/standard/standard/issues/1868

**Comment by qodunpob** [comment]
> Removing this rule doesn't seem reasonable

We can't relay on a broken rule
